# Generated by Django 3.1.5 on 2022-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mask', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('vlan', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
