# Generated by Django 3.1.5 on 2022-01-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=100)),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subnet.subnet')),
            ],
        ),
    ]
