# Generated by Django 3.1.5 on 2022-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subnet', '0002_reservedip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subnet',
            old_name='ip',
            new_name='network_id',
        ),
        migrations.RenameField(
            model_name='subnet',
            old_name='vlan',
            new_name='vlan_id',
        ),
        migrations.AddField(
            model_name='subnet',
            name='ip_end_range',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
